### ISSUE TITLE
Video stuttering when bitrate is set to 720p

### ISSUE THREAD

**Issue by Thrius** [TwitchedApp/Twitched#31]
### Description
When the quality bitrate is set to 720p any stream or VOD has stuttering video a few times a second

### Steps to Reproduce
1. From Twitched app on Roku verify quality setting is at 720p
2. Open a stream or VOD
3. Notice the video is stuttering every few times a second

**Expected behavior:** [What was supposed to happen]
Video stream displays as it should without any noticeable stuttering

**Actual behavior:** [What actually happened]
Video is stuttering a few times a second

**Roku Model:** [Model]
4630X Roku Premiere+

**Roku Firmware Version:** [Firmware version] 
8.1.0 build 4137-29

**Twitched Version:** [Version number]
1.4 I believe, or most recent as I tried reinstalling the app

### Additional Information
When video quality is set to automatic, 1080p or 480p the video streams display as they should. It seems only 720p is affected. Possibly a 720p 60fps issue? I've been using 720p with the twitched app and the video has displayed fine, so seems to be a new issue.

**Comment by rolandoislas** [comment]
Does this happen on all channels?

**Comment by Thrius** [comment]
@rolandoislas Not all channels, no. Some Twitch channels when set to quality of 720p reproduce the issue: Lirik, CohhCarnage and Stodeh. The issue did not reproduce on channels: CDNThe3rd and TheRealShooKon3 for instance.

**Comment by Tibbetts24** [comment]
CohhCarnage streams at 60fps.  It could be your Roku that is the problem.  With Twitched I've had no problems watching 60fps streams.

**Comment by rolandoislas** [comment]
I am not sure if Twitch changed their encoding settings or if this is related to the Roku OS 8.1 update, but 720p60 is skipping frames on the Roku 4660X as well. It only affects some models, as the 3710X plays both 1080p60 and 720p60 fine. 

This is likely only affecting 720p60 because it is the usually the only 60 FPS stream variant encoded by Twitch. A 1080p60 stream would pass through as the source stream and it would be encoded down to 720p60, 480p30, etc.

An update will be released soon to disable 720p60 while still retaining the ability to watch 1080p60 and 720p30 on models 4630X and 4660X.

**Comment by Thrius** [comment]
@rolandoislas The fix resolved the issue. I tried the Twitch stream channels mentioned in this ticket and a few others using 720p and then 1080p for the quality. Everything looked good with no stuttering or dropped frames. Thank you!
