### ISSUE TITLE
Do streams experience lag/stutter on Roku stick 3600r like former Twitch app?

### ISSUE THREAD

**Issue by seanbperiod** [TwitchedApp/Twitched#9]
I was just wondering about the performance of this app vs the original app for Roku players. I still have the original Twitch app on the Roku stick 3600r, but experience frequent low quality pixelations, stutter, and lag on video. 

Before I purchase, are these issues eliminated on this app?

**Comment by rolandoislas** [comment]
I need a beta tester for the Roku Streaming Stick (Briscoe 3600X). If you are interested please send an email to support@twitched.org with an email address linked to a Roku account that can be added as a test user.

Specifically, I need to test if the 1920x1080 resolution streams at 60 FPS can play without stuttering and desyncing their audio and video. Ideally, a download bandwidth of equal to or greater than 7 mbps would allow for 1080p streaming.

**Comment by jbaconbits** [comment]
The regular streaming sticks won't be able to play back 1080p60 video reliably. 

Basically any Roku model that has a max UI resolution of 720p (so all non-4k models) are limited to 720p60 or 1080p30.

**Comment by rolandoislas** [comment]
@jbaconbits This is not the case with the Littlefield (3710X - Roku Express Plus) which has hardware similar to the Briscoe (3600X - Streaming Stick).

Something to consider is the Littlefield does appear to stutter on streams with a bitrate greater than 8 mbps. Testing a stream at ~7.85 mbps did not cause the stuttering to occur. A lot of streams keep around 6 mbps likely since it is the [max bitrate recommended by Twitch](https://stream.twitch.tv/encoding/) for 1080p60 streams.

I would rather disable 8+ mbps streams only instead of all 1080p60 streams on the lower-end devices that can still support 60 fps at less than 8 mbps.
